### PR TITLE
Fix Debug build on Ubuntu 18.04+ (faulty protobuf 3.0 version)

### LINKED ISSUE #2343: Unused parameter 'deterministic'
<b>OS:</b>
Ubuntu 16.04 (in Docker)

<b>Cockatrice version:</b>
latest (hash is useless b/c of unrelated local commits)

___
<br>

When building Cockatrice in a Docker container after configuring with `cmake .. -DWITH_SERVER=1 -DTEST=1 -DCMAKE_BUILD_TYPE=Debug`, I get the following error:

```
Scanning dependencies of target cockatrice_protocol
[ 31%] Building CXX object common/pb/CMakeFiles/cockatrice_protocol.dir/admin_commands.pb.cc.o
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual google::protobuf::uint8* AdminCommand::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:367:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual bool AdminCommand::IsInitialized() const':
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:443:3: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
   if (!_extensions_.IsInitialized()) return false;  return true;
   ^~
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:443:53: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
   if (!_extensions_.IsInitialized()) return false;  return true;
                                                     ^~~~~~
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual google::protobuf::uint8* Command_UpdateServerMessage::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:583:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual google::protobuf::uint8* Command_ShutdownServer::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:853:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual google::protobuf::uint8* Command_ReloadConfig::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:1182:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual google::protobuf::uint8* Command_AdjustMod::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:1452:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
common/pb/CMakeFiles/cockatrice_protocol.dir/build.make:1278: recipe for target 'common/pb/CMakeFiles/cockatrice_protocol.dir/admin_commands.pb.cc.o' failed
make[2]: *** [common/pb/CMakeFiles/cockatrice_protocol.dir/admin_commands.pb.cc.o] Error 1
CMakeFiles/Makefile2:1073: recipe for target 'common/pb/CMakeFiles/cockatrice_protocol.dir/all' failed
make[1]: *** [common/pb/CMakeFiles/cockatrice_protocol.dir/all] Error 2
```

This doesn't happen when building in Release mode in an identical container.

Full build log: https://gitlab.tetrarch.co/cockatrice/cockatrice/builds/714

### PR DESCRIPTION
**Pull request by berserkingyadis**
## Related Ticket(s)
- Fixes #2343

## Short roundup of the initial problem
Due to the faulty protobuf version which is installed by default on Ubuntu 18.04 and 18.10 (discussed in #2343 ), the current cmake configuration throws warning-errors for `unused-parameter` and `misleading-indentation` in the protobuf generated code in Debug build.

Compiler log:
```
Scanning dependencies of target cockatrice_protocol
[ 31%] Building CXX object common/pb/CMakeFiles/cockatrice_protocol.dir/admin_commands.pb.cc.o
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual google::protobuf::uint8* AdminCommand::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:367:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual bool AdminCommand::IsInitialized() const':
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:443:3: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
   if (!_extensions_.IsInitialized()) return false;  return true;
   ^~
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:443:53: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
   if (!_extensions_.IsInitialized()) return false;  return true;
                                                     ^~~~~~
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual google::protobuf::uint8* Command_UpdateServerMessage::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:583:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual google::protobuf::uint8* Command_ShutdownServer::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:853:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual google::protobuf::uint8* Command_ReloadConfig::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:1182:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual google::protobuf::uint8* Command_AdjustMod::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
/builds/cockatrice/cockatrice/build/common/pb/admin_commands.pb.cc:1452:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
common/pb/CMakeFiles/cockatrice_protocol.dir/build.make:1278: recipe for target 'common/pb/CMakeFiles/cockatrice_protocol.dir/admin_commands.pb.cc.o' failed
make[2]: *** [common/pb/CMakeFiles/cockatrice_protocol.dir/admin_commands.pb.cc.o] Error 1
CMakeFiles/Makefile2:1073: recipe for target 'common/pb/CMakeFiles/cockatrice_protocol.dir/all' failed
make[1]: *** [common/pb/CMakeFiles/cockatrice_protocol.dir/all] Error 2
```

## What will change with this Pull Request?
The 2 warning-errors mentioned above and in #2343 will not be treated as errors anymore.

### CODE REVIEW

**Comment by ctrlaltca** [comment]
We reason why we currently have a debug build target is to catch such errors; muting them by adding these flags would mean that the Travis builds won't fail anymore if such problems are found in the code.

This case is unfortunate because the code causing problems is not written by us, but autogenerated by - a specific, known broken version of - the protobuf compiler. Blame on the ubuntu team for bundling bleeding edge version of software (3.0.0) and [sitting on bug reports for one year](https://bugs.launchpad.net/ubuntu/+source/protobuf/+bug/1643959).
I see a few possible workarounds here:

1. add a cmake option that disabled that check, or that disables "treat warning as errors" at all;
2. try to maintain a list of broken distributions / protobuf versions, detect them and automatically disable that check; 
3. just declare that the protobuf package on ubuntu is currently broken and you actually can't compile a debug version on it without getting your hands dirty.

**Comment by Daenyth** [comment]
If we exposed a flag cmake flag that allows a developer to disable "warnings as errors" that might be helpful. Then we could leave the useful checks in place and tell people using a broken protoc to flip that flag on so they can compile. I think we should go that route since we can't just blanket disable warnings for all proto files.

**Comment by ctrlaltca** [comment]
Closing in favour of #3275
