### ISSUE TITLE
Servatrice failing to compile on VS2017 after ccee0aa

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#2877]
As of https://github.com/Cockatrice/Cockatrice/commit/ccee0aa3fd7dfc77ef7ac246f8905cbf72ae8eba when attempting to compile servatrice using VS2017 it begins to fail with the following: 

```
5>------ Build started: Project: servatrice, Configuration: Release Win32 ------
5>version_string.cpp
5>MSVCRT.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol _WinMain@16 referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)
5>C:\Cockatrice\build\servatrice\Release\servatrice.exe : fatal error LNK1120: 1 unresolved externals
5>Done building project "servatrice.vcxproj" -- FAILED.
========== Build: 4 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========
```

Doing some quick searching it may have to do with some flags the possibly were removed with the commit.  I found a similar issue reported by some one else for another project at (https://stackoverflow.com/questions/39689162/qt-project-in-visual-studio-2015-unresolved-external-symbol-wwinmain)

Rolling back to the commit prior to this results in a successful compile.

**Comment by ctrlaltca** [comment]
Quick suggestion: try to update cmake if outdated

**Comment by woogerboy21** [comment]
Im running 3.9, what version do you recommend?

**Comment by ctrlaltca** [comment]
You are right. Cmake should automatically understand that servatrice needs to be linked to Qt's WinMain, it actually works for Cockatrice and Oracle but not for servatrice (maybe because it's a console application with no gui?).
Sorry for the delay, it took some time to setup a VS 2017 + Qt 5.9.1 + Cmake 3.93 development environment and test this.

**Comment by woogerboy21** [comment]
No problem, we all get busy.  I just threw 5.9.1 on my box last night but have yet to compile against it.  Any particular reason you started using 5.9.1?

**Comment by ctrlaltca** [comment]
Qt 5.6.x was the latest "long term support" release, 5.7 and 5.8 were rushed releases with almost no bugfixes in, 5.9.x is the new "LTS" release. It's probably what we want to support for the next few years.
I'm also experimenting with protobuf3, still using the proto2 wire format to keep backwards compatibility.

**Comment by Daenyth** [comment]
I'm not sure it's possible for us to use proto3 because we use extensions and they were removed. Have you found differently?

**Comment by ctrlaltca** [comment]
As long as your files are using the "proto2" syntax, you can still use them.

**Comment by woogerboy21** [comment]
I originally had that declaration in the proto files and I believe @Daenyth rolled the change back for one reason or another

**Comment by ctrlaltca** [comment]
Yep, they were reintroduced later in https://github.com/Cockatrice/Cockatrice/pull/2313

**Comment by woogerboy21** [comment]
Cool 👍
